<?php

return [
    [1, 'US Dollar', 'USD', '$', true],
    [2, 'Euro', 'EUR', '€', false],
    [3, 'British Pound', 'GBP', '£', false],
    [4, 'Japanese Yen', 'JPY', '¥', false],
    [5, 'Canadian Dollar', 'CAD', 'C$', false],
    [6, 'Australian Dollar', 'AUD', 'A$', false],
    [7, 'Swiss Franc', 'CHF', 'CHF', false],
    [8, 'Chinese Yuan', 'CNY', '¥', false],
    [9, 'Indian Rupee', 'INR', '₹', false],
    [10, 'South Korean Won', 'KRW', '₩', false],
    [11, 'Mexican Peso', 'MXN', '$', false],
    [12, 'Brazilian Real', 'BRL', 'R$', false],
    [13, 'Russian Ruble', 'RUB', '₽', false],
    [14, 'South African Rand', 'ZAR', 'R', false],
    [15, 'Singapore Dollar', 'SGD', 'S$', false],
    [16, 'Hong Kong Dollar', 'HKD', 'HK$', false],
    [17, 'Norwegian Krone', 'NOK', 'kr', false],
    [18, 'Swedish Krona', 'SEK', 'kr', false],
    [19, 'Danish Krone', 'DKK', 'kr', false],
    [20, 'Polish Zloty', 'PLN', 'zł', false],
    [21, 'Turkish Lira', 'TRY', '₺', false],
    [22, 'Thai Baht', 'THB', '฿', false],
    [23, 'New Zealand Dollar', 'NZD', 'NZ$', false],
    [24, 'Israeli Shekel', 'ILS', '₪', false],
    [25, 'UAE Dirham', 'AED', 'د.إ', false],
    [26, 'Saudi Riyal', 'SAR', '﷼', false],
    [27, 'Egyptian Pound', 'EGP', '£', false],
    [28, 'Nigerian Naira', 'NGN', '₦', false],
    [29, 'Kenyan Shilling', 'KES', 'KSh', false],
    [30, 'Philippine Peso', 'PHP', '₱', false],
    [31, 'Afghan Afghani', 'AFN', '؋', false],
    [32, 'Albanian Lek', 'ALL', 'L', false],
    [33, 'Algerian Dinar', 'DZD', 'د.ج', false],
    [34, 'Angolan Kwanza', 'AOA', 'Kz', false],
    [35, 'Argentine Peso', 'ARS', '$', false],
    [36, 'Armenian Dram', 'AMD', '֏', false],
    [37, 'Aruban Florin', 'AWG', 'ƒ', false],
    [38, 'Azerbaijani Manat', 'AZN', '₼', false],
    [39, 'Bahamian Dollar', 'BSD', '$', false],
    [40, 'Bahraini Dinar', 'BHD', '.د.ب', false],
    [41, 'Bangladeshi Taka', 'BDT', '৳', false],
    [42, 'Barbadian Dollar', 'BBD', '$', false],
    [43, 'Belarusian Ruble', 'BYN', 'Br', false],
    [44, 'Belize Dollar', 'BZD', '$', false],
    [45, 'Bermudian Dollar', 'BMD', '$', false],
    [46, 'Bhutanese Ngultrum', 'BTN', 'Nu.', false],
    [47, 'Bolivian Boliviano', 'BOB', 'Bs.', false],
    [48, 'Bosnia-Herzegovina Convertible Mark', 'BAM', 'KM', false],
    [49, 'Botswanan Pula', 'BWP', 'P', false],
    [50, 'Brunei Dollar', 'BND', '$', false],
    [51, 'Bulgarian Lev', 'BGN', 'лв', false],
    [52, 'Burundian Franc', 'BIF', 'Fr', false],
    [53, 'Cambodian Riel', 'KHR', '៛', false],
    [54, 'Cape Verdean Escudo', 'CVE', '$', false],
    [55, 'Cayman Islands Dollar', 'KYD', '$', false],
    [56, 'Central African CFA Franc', 'XAF', 'Fr', false],
    [57, 'CFP Franc', 'XPF', 'Fr', false],
    [58, 'Chilean Peso', 'CLP', '$', false],
    [59, 'Colombian Peso', 'COP', '$', false],
    [60, 'Comorian Franc', 'KMF', 'Fr', false],
    [61, 'Congolese Franc', 'CDF', 'Fr', false],
    [62, 'Costa Rican Colón', 'CRC', '₡', false],
    [63, 'Croatian Kuna', 'HRK', 'kn', false],
    [64, 'Cuban Peso', 'CUP', '$', false],
    [65, 'Czech Koruna', 'CZK', 'Kč', false],
    [66, 'Djiboutian Franc', 'DJF', 'Fr', false],
    [67, 'Dominican Peso', 'DOP', '$', false],
    [68, 'East Caribbean Dollar', 'XCD', '$', false],
    [69, 'Eritrean Nakfa', 'ERN', 'Nfk', false],
    [70, 'Ethiopian Birr', 'ETB', 'Br', false],
    [71, 'Falkland Islands Pound', 'FKP', '£', false],
    [72, 'Faroese Króna', 'FOK', 'kr', false],
    [73, 'Fijian Dollar', 'FJD', '$', false],
    [74, 'Gambian Dalasi', 'GMD', 'D', false],
    [75, 'Georgian Lari', 'GEL', '₾', false],
    [76, 'Ghanaian Cedi', 'GHS', '₵', false],
    [77, 'Gibraltar Pound', 'GIP', '£', false],
    [78, 'Guatemalan Quetzal', 'GTQ', 'Q', false],
    [79, 'Guinean Franc', 'GNF', 'Fr', false],
    [80, 'Guyanaese Dollar', 'GYD', '$', false],
    [81, 'Haitian Gourde', 'HTG', 'G', false],
    [82, 'Honduran Lempira', 'HNL', 'L', false],
    [83, 'Hungarian Forint', 'HUF', 'Ft', false],
    [84, 'Icelandic Króna', 'ISK', 'kr', false],
    [85, 'Indonesian Rupiah', 'IDR', 'Rp', false],
    [86, 'Iranian Rial', 'IRR', '﷼', false],
    [87, 'Iraqi Dinar', 'IQD', 'ع.د', false],
    [88, 'Jamaican Dollar', 'JMD', '$', false],
    [89, 'Jordanian Dinar', 'JOD', 'د.ا', false],
    [90, 'Kazakhstani Tenge', 'KZT', '₸', false],
    [91, 'Kuwaiti Dinar', 'KWD', 'د.ك', false],
    [92, 'Kyrgystani Som', 'KGS', 'с', false],
    [93, 'Laotian Kip', 'LAK', '₭', false],
    [94, 'Lebanese Pound', 'LBP', 'ل.ل', false],
    [95, 'Lesotho Loti', 'LSL', 'L', false],
    [96, 'Liberian Dollar', 'LRD', '$', false],
    [97, 'Libyan Dinar', 'LYD', 'ل.د', false],
    [98, 'Macanese Pataca', 'MOP', 'P', false],
    [99, 'Macedonian Denar', 'MKD', 'ден', false],
    [100, 'Malagasy Ariary', 'MGA', 'Ar', false],
    [101, 'Malawian Kwacha', 'MWK', 'MK', false],
    [102, 'Malaysian Ringgit', 'MYR', 'RM', false],
    [103, 'Maldivian Rufiyaa', 'MVR', '.ރ', false],
    [104, 'Mauritanian Ouguiya', 'MRU', 'UM', false],
    [105, 'Mauritian Rupee', 'MUR', '₨', false],
    [106, 'Moldovan Leu', 'MDL', 'L', false],
    [107, 'Mongolian Tugrik', 'MNT', '₮', false],
    [108, 'Moroccan Dirham', 'MAD', 'د.م.', false],
    [109, 'Mozambican Metical', 'MZN', 'MT', false],
    [110, 'Myanmar Kyat', 'MMK', 'Ks', false],
    [111, 'Namibian Dollar', 'NAD', '$', false],
    [112, 'Nepalese Rupee', 'NPR', '₨', false],
    [113, 'Netherlands Antillean Guilder', 'ANG', 'ƒ', false],
    [114, 'Nicaraguan Córdoba', 'NIO', 'C$', false],
    [115, 'North Korean Won', 'KPW', '₩', false],
    [116, 'Omani Rial', 'OMR', 'ر.ع.', false],
    [117, 'Pakistani Rupee', 'PKR', '₨', false],
    [118, 'Panamanian Balboa', 'PAB', 'B/.', false],
    [119, 'Papua New Guinean Kina', 'PGK', 'K', false],
    [120, 'Paraguayan Guarani', 'PYG', '₲', false],
    [121, 'Peruvian Nuevo Sol', 'PEN', 'S/.', false],
    [122, 'Qatari Rial', 'QAR', 'ر.ق', false],
    [123, 'Romanian Leu', 'RON', 'lei', false],
    [124, 'Rwandan Franc', 'RWF', 'Fr', false],
    [125, 'Saint Helena Pound', 'SHP', '£', false],
    [126, 'Samoan Tala', 'WST', 'T', false],
    [127, 'São Tomé and Príncipe Dobra', 'STN', 'Db', false],
    [128, 'Serbian Dinar', 'RSD', 'дин.', false],
    [129, 'Seychellois Rupee', 'SCR', '₨', false],
    [130, 'Sierra Leonean Leone', 'SLL', 'Le', false],
    [131, 'Solomon Islands Dollar', 'SBD', '$', false],
    [132, 'Somali Shilling', 'SOS', 'Sh', false],
    [133, 'Sri Lankan Rupee', 'LKR', '₨', false],
    [134, 'Sudanese Pound', 'SDG', 'ج.س.', false],
    [135, 'Surinamese Dollar', 'SRD', '$', false],
    [136, 'Swazi Lilangeni', 'SZL', 'L', false],
    [137, 'Syrian Pound', 'SYP', '£', false],
    [138, 'Taiwanese New Dollar', 'TWD', 'NT$', false],
    [139, 'Tajikistani Somoni', 'TJS', 'ЅМ', false],
    [140, 'Tanzanian Shilling', 'TZS', 'Sh', false],
    [141, 'Tongan Paʻanga', 'TOP', 'T$', false],
    [142, 'Trinidad and Tobago Dollar', 'TTD', '$', false],
    [143, 'Tunisian Dinar', 'TND', 'د.ت', false],
    [144, 'Turkmenistani Manat', 'TMT', 'm', false],
    [145, 'Ugandan Shilling', 'UGX', 'Sh', false],
    [146, 'Ukrainian Hryvnia', 'UAH', '₴', false],
    [147, 'Uruguayan Peso', 'UYU', '$', false],
    [148, 'Uzbekistan Som', 'UZS', 'сўм', false],
    [149, 'Vanuatu Vatu', 'VUV', 'Vt', false],
    [150, 'Venezuelan Bolívar', 'VES', 'Bs.S.', false],
    [151, 'Vietnamese Dong', 'VND', '₫', false],
    [152, 'West African CFA Franc', 'XOF', 'Fr', false],
    [153, 'Yemeni Rial', 'YER', '﷼', false],
    [154, 'Zambian Kwacha', 'ZMW', 'ZK', false],
    [155, 'Zimbabwean Dollar', 'ZWL', '$', false],
];
